class/actions_supplierorderfromorder.class.php
ordercustomer.php

Liaison du projet de la commande client sur la commande fournisseur lors de sa génération

Liaison du projet de la commande client sur la commande fournisseur 

---

admin/supplierorderfromorder_setup.php
langs/fr_FR/supplierorderfromorder.lang
ordercustomer.php

ajout conf pour gestion de la creation des commandes en fonction du projet

new_managing_distrib_product_by_project

---

ordercustomer.php

Fix 6.0 paramètre obligatoire

---

langs/fr_FR/supplierorderfromorder.lang
ordercustomer.php

Issue #1 
Pouvoir sélectionner un fournisseur pour tous les produits

NEW : Select supplier for all products

---

admin/dispatch_to_supplier_order_setup.php
admin/supplierorderfromorder_setup.php
class/actions_supplierorderfromorder.class.php
config.php
core/modules/modSupplierorderfromorder.class.php
core/triggers/interface_99_modSupplierorderfromorder_supplierorderfromorder.class.php
css/style.css
dispatch_to_supplier_order.php
js/dispatch_to_supplier_order.js.php
langs/fr_FR/supplierorderfromorder.lang
lib/function.lib.php
ordercustomer.php

Permet d'ajouter un nouvel onglet permettant de gérer la partie nomenclature

New dispatch script for nomenclature

---

config.default.php
config.php

use the standard init like other "newer" ATM modules

use modern entrypoint to start config - ATM standard

---

ordercustomer.php
script/interface.php

FIX TK12573 : Erreur de calcul sur la qté quand le stock virtuel activé + Dédoublonnage quand plusieurs fois le meme produit dans la même commande

 FIX TK12573 : Erreur de calcul sur la qté quand le stock virtuel activé + Dédoublonnage quand plusieurs fois le meme produit dans la même commande

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
script/interface.php

Compatibility V13 - add token renowal

FIX : add token renowal

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
js/dispatch_to_supplier_order.js.php
ordercustomer.php
script/interface.php

cf. https://github.com/ATM-Consulting/dolibarr_module_supplierorderfromorder/pull/63

(PULLUP) NEW: compatibilité v14

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
js/dispatch_to_supplier_order.js.php
ordercustomer.php
script/interface.php

Changé:
- NOCSRFCHECK
- descripteur de module
- setDateLivraison
- ChangeLog

NEW: compatibilité v14

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
dispatch_to_supplier_order.php
langs/fr_FR/supplierorderfromorder.lang

2.0 fix dispatch soc detection

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
dispatch_to_supplier_order.php
langs/fr_FR/supplierorderfromorder.lang

PULL UP : 2.0 fix dispatch soc detection

---

ChangeLog.md
admin/dispatch_to_supplier_order_setup.php
core/modules/modSupplierorderfromorder.class.php
dispatch_to_supplier_order.php
js/dispatch_to_supplier_order.js.php
langs/fr_FR/supplierorderfromorder.lang
lib/function.lib.php

- Fix : bad if conditions
- Fix : refacto de batard
- Fix : treatment after error validation
- New : Add sub-nomenclature view (+ conf)
- Fix : link nomenclature lines to supplier order line

Fix 2.0 nomenclature

---

ChangeLog.md
admin/dispatch_to_supplier_order_setup.php
core/modules/modSupplierorderfromorder.class.php
dispatch_to_supplier_order.php
js/dispatch_to_supplier_order.js.php
langs/fr_FR/supplierorderfromorder.lang
lib/function.lib.php

- Fix : bad if conditions
- Fix : refacto de batard
- Fix : treatment after error validation
- New : Add sub-nomenclature view (+ conf)
- Fix : link nomenclature lines to supplier order line

PULL UP : Fix 2.0 nomenclature

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
ordercustomer.php

S'il y a une remise fournisseur celle-ci n'était pas appliquée

FIX supplier discount (remise fournisseur)

---

ChangeLog.md
admin/supplierorderfromorder_setup.php
class/actions_supplierorderfromorder.class.php
class/sofo.class.php
core/modules/modSupplierorderfromorder.class.php
dispatch_to_supplier_order.php
langs/fr_FR/supplierorderfromorder.lang
lib/function.lib.php
ordercustomer.php

restrict input and redirection to sorted list cmd fourn

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
ordercustomer.php

NEW : add hook

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
lib/function.lib.php

: change params passed to find_min_price_product_fournisseur ($productid instaed of $line->fk_product)

FIX  change params passed to find_min_price_product_fournisseur

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
ordercustomer.php

add exit on header location

---

cbn.php
langs/de_DE/supplierorderfromorder.lang
langs/en_US/supplierorderfromorder.lang
langs/fr_FR/supplierorderfromorder.lang
ordercustomer.php

Buttons where not translatable before.

Buttons now translatable

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
ordercustomer.php

FIX : DA023344 - Wrong virtual stock

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
ordercustomer.php

see : https://github.com/ATM-Consulting/dolibarr_module_supplierorderfromorder/pull/130

PULLUP [main] | FIX : DA023344 - Wrong virtual stock main

---

ChangeLog.md
class/sofo.class.php
core/modules/modSupplierorderfromorder.class.php
ordercustomer.php

PULL UP main : Fix php warnings da02684

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
lib/function.lib.php

created a clone from the initial line instead.

remove overwritting initial orderline product in cmdfourn create

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
dispatch_to_supplier_order.php

PULLUP [main] | FIX : Warning on supplier order page

---

ChangeLog.md
admin/supplierorderfromorder_setup.php
core/modules/modSupplierorderfromorder.class.php
langs/fr_FR/supplierorderfromorder.lang
ordercustomer.php

nouvelle feature permettant d'ajouter les notes privées ou publiques de la commande client vers la commande fournisseur

New add notes

---

ChangeLog.md
config.default.php
core/modules/modSupplierorderfromorder.class.php

FIX : DA024990 - Suppression de is_file intuiles 

---

ChangeLog.md
config.default.php

Voir : https://github.com/ATM-Consulting/dolibarr_module_supplierorderfromorder/pull/149

PULLUP [main] | FIX : DA024990 - Suppression de is_file intuiles

---

ChangeLog.md
admin/supplierorderfromorder_setup.php
langs/fr_FR/supplierorderfromorder.lang
ordercustomer.php

Ajout de la description des produits lors de la création d'une facture fournisseur (soumis a conf)

NEW - Description produits

---

ChangeLog.md
core/modules/modSupplierorderfromorder.class.php
ordercustomer.php

[v](https://github.com/ATM-Consulting/dolibarr_module_supplierorderfromorder/pull/170)

PULLUP - FIX - COMPAT v21 
